Update twine-validator.txt
Digitaler-Impfnachweis/covpass-apps-i18n pull request #13
Opened 2021-07-16 12:11 UTC by LisaGumprich

2021-07-19 14:56 UTC, timokoenig requested changes

2021-07-19 14:56 UTC, timokoenig commented on twine-validator.txt
> +en = Version %d
Should be `Version %@`

2021-07-21 13:43 UTC, LisaGumprich commented on twine-validator.txt
> +en = Version %d
Done! :)

2021-07-21 14:30 UTC, timokoenig commented on twine-validator.txt
> +en = Negative rapid test from %@ hours ago
Please use format as in German translation: `%d`

2021-07-21 14:30 UTC, timokoenig commented on twine-validator.txt
> +en = Negative PCR test from %@ hours ago
Please use format as in German translation: `%d`

2021-07-21 15:12 UTC, timokoenig approved these changes

2021-07-21 15:13 UTC, merged