Updated links in covpass
Digitaler-Impfnachweis/covpass-apps-i18n pull request #329
Opened 2023-01-18 13:03 UTC by RaulMeer

2023-01-18 13:11 UTC, Ein-Tim requested changes

2023-01-18 13:11 UTC, Ein-Tim commented on twine-cert.txt
> +    de = #Mehr in den häufigen Fragen::https://www.digitaler-impfnachweis-app.de/faq/#die-aktuell-h-ufigsten-fragen#
Missing "Informationen"

2023-01-18 13:11 UTC, Ein-Tim commented on twine-cert.txt
> +    de = #Mehr in den häufigen Fragen::https://www.digitaler-impfnachweis-app.de/faq/#die-aktuell-h-ufigsten-fragen#
Missing "Informationen"

2023-01-18 13:11 UTC, Ein-Tim commented on twine-cert.txt
> +    de = #Mehr in den häufigen Fragen::https://www.digitaler-impfnachweis-app.de/faq/#die-aktuell-h-ufigsten-fragen#
Missing "Informationen"

2023-01-18 13:11 UTC, Ein-Tim commented on twine-cert.txt
> +    de = #Mehr in den häufigen Fragen::https://www.digitaler-impfnachweis-app.de/faq/#die-aktuell-h-ufigsten-fragen#
Missing "Informationen"

2023-01-19 11:03 UTC, RaulMeer reviewed
changed wording for faq links after feedback

2023-01-19 12:33 UTC, Ein-Tim approved these changes
Looks good now!

2023-01-19 15:17 UTC, merged